-- MySQL Script generated by MySQL Workbench
-- Fri Jun  9 09:45:15 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema games
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema games
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `games` DEFAULT CHARACTER SET utf8 ;
USE `games` ;

-- -----------------------------------------------------
-- Table `games`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `games`.`Item` (
  `item_id` INT NOT NULL,
  `item_name` VARCHAR(45) NULL,
  `item_rating` VARCHAR(45) NULL,
  PRIMARY KEY (`item_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

/*
-- Query: 
-- Date: 2017-06-09 09:52
*/
INSERT INTO `item` (`item_id`,`item_name`,`item_rating`) VALUES (1,'Kingdom Hearts','E10+');
INSERT INTO `item` (`item_id`,`item_name`,`item_rating`) VALUES (2,'StarCraft','T');
INSERT INTO `item` (`item_id`,`item_name`,`item_rating`) VALUES (3,'Super Mario World','E');
INSERT INTO `item` (`item_id`,`item_name`,`item_rating`) VALUES (4,'Zelda: Ocarina of Time','E');
